### ISSUE TITLE
AUC 95% interval obtained by bootstrapping seems off

### ISSUE THREAD

**Issue by siemdejong** [hirsch-lab/roc-utils#3]
I can successfully plot the confidence band around an ROC curve and the interval is plausible.

However, the corresponding confidence interval on the AUC is questionable. Looking at the shaded area, I expect to have an AUC interval of something like [0.6, 1]. Is the CI to be expected?

```
AUC 95% CI: [[0.89360685 0.89723678]]
```
![image](https://github.com/hirsch-lab/roc-utils/assets/28396796/a79454b2-9097-46a6-8795-ccc6bb857f56)

MWE:
```python
import matplotlib.pyplot as plt
import roc_utils as ru

preds = np.array([0.0184128433465957, 0.012704842723906, 0.6588426828384399, 0.3824790120124817, 0.0752698183059692, 0.0284929275512695, 0.0939247459173202, 0.0913288220763206, 0.1392715573310852, 0.8083584308624268, 0.5678479075431824, 0.7689659595489502, 0.6002992391586304, 0.4453626573085785])
targets = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])

results = ru.plot_roc_bootstrap(X=preds, y=targets, pos_label=1,
                      n_bootstrap=9999,
)
plt.show()
print("AUC 95% CI:", results["auc95_ci"])
```

**Comment by siemdejong** [comment]
Apparently, the grey area shows the tolerance interval and not the confidence interval, as revealed when using less samples. I suggest adding this information in the legend.
![image](https://github.com/hirsch-lab/roc-utils/assets/28396796/3ee1d6a3-9ad7-4fa0-9d89-6eec5259c314)

**Comment by normanius** [comment]
The documentation is not the best, but I plan to refactor some parts of the package at some point. Improving the docs is on my list, too.

Adding the information in the legend makes it rather cluttered. However, showing the information optionally and displaying it in the demo or the README could certainly be helpful. I'll consider that.
